using Samples.Identity.Controllers;

namespace Samples.Identity.Test.Controllers;

public class AccountControllerTests
{
    /// <summary>
    /// We rely on the fact that an encoded token can round-trip and be decoded
    /// at the other end.
    /// </summary>
    [Fact]
    public void EncodeDecodeTokenRoundtrips()
    {
        // This is a token that has been previously generated by ASP.NET Identity, so it's indicative of the token.
        const string token = "CfDJ8DRxAjs2vUtIk+BtbpTyhGrE8Y/PDoRWBwJYvvHQSMljfmRRHLPdPWGpwNomlb6FMqZH6Ssgrfwxh9YTRPRl6izsYRVphPy0LUECnLz95bNX4MIsrLFM3LxJhcyZJsD8x0HS7JRn5n83SXDKBTgUmV2YnU3cvrIzcc2973kFNbK5yYPL+vTxWFuKGAB+TCZTnhj7Yfue0O21BQFFQi1exDfL5OB1bx3vqxrPghhm0EZX";

        string code = AccountController.EncodeToken(token);
        string result = AccountController.DecodeToken(code);
        Assert.Equal(token, result);
    }
}
